import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const ThemeCreatorApp());
}

class ThemeCreatorApp extends StatelessWidget {
  const ThemeCreatorApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Theme Creator & XML Studio',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),
      home: const ThemeStudioScreen(),
    );
  }
}

class ThemeStudioScreen extends StatefulWidget {
  const ThemeStudioScreen({Key? key}) : super(key: key);

  @override
  State<ThemeStudioScreen> createState() => _ThemeStudioScreenState();
}

class _ThemeStudioScreenState extends State<ThemeStudioScreen> {
  Color _backgroundColor = const Color(0xFF0D0D0D);
  Color _headerColor = const Color(0xFF121212);
  Color _surfaceColor = const Color(0xFF181818);
  Color _primaryColor = const Color(0xFF4DEAEA);
  Color _secondaryColor = const Color(0xFF2196F3);
  Color _tertiaryColor = const Color(0xFF00FF66);
  Color _warningColor = const Color(0xFFFFB74D);
  Color _dangerColor = const Color(0xFFFF5252);
  Color _textColor = Colors.white;

  String get _generatedXml {
    String hex(Color c) => "#${c.value.toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}";

    return '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by App Manager Theme Studio -->
<resources>
    <style name="Theme.CustomApp" parent="Theme.Material3.DayNight.NoActionBar">
        <!-- Main Brand Colors -->
        <item name="colorPrimary">${hex(_primaryColor)}</item>
        <item name="colorSecondary">${hex(_secondaryColor)}</item>
        <item name="colorTertiary">${hex(_tertiaryColor)}</item>

        <!-- Surfaces & Backgrounds -->
        <item name="android:colorBackground">${hex(_backgroundColor)}</item>
        <item name="colorSurface">${hex(_surfaceColor)}</item>
        <item name="colorSurfaceVariant">${hex(_headerColor)}</item>

        <!-- Status & Accents -->
        <item name="colorError">${hex(_dangerColor)}</item>
        <item name="colorWarning">${hex(_warningColor)}</item>

        <!-- Text & Typography -->
        <item name="colorOnBackground">${hex(_textColor)}</item>
        <item name="colorOnSurface">${hex(_textColor)}</item>
    </style>
</resources>''';
  }

  void _applyPreset(Color bg, Color header, Color surface, Color pri, Color sec, Color ter) {
    setState(() {
      _backgroundColor = bg;
      _headerColor = header;
      _surfaceColor = surface;
      _primaryColor = pri;
      _secondaryColor = sec;
      _tertiaryColor = ter;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _backgroundColor,
      appBar: AppBar(
        backgroundColor: _headerColor,
        title: Row(
          children: [
            Icon(Icons.palette, color: _primaryColor),
            const SizedBox(width: 8),
            const Text('THEME CREATOR & LIVE XML STUDIO', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ],
        ),
        actions: [
          ElevatedButton.icon(
            style: ElevatedButton.styleFrom(backgroundColor: _primaryColor, foregroundColor: Colors.black),
            onPressed: () {
              Clipboard.setData(ClipboardData(text: _generatedXml));
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('📋 XML Theme copied to clipboard! Hand it to Antigravity assistant.')),
              );
            },
            icon: const Icon(Icons.copy, size: 16),
            label: const Text('COPY XML THEME', style: TextStyle(fontWeight: FontWeight.bold)),
          ),
          const SizedBox(width: 12),
        ],
      ),
      body: Row(
        children: [
          // Left Sidebar: Color Controls & Presets
          Container(
            width: 320,
            color: _headerColor,
            padding: const EdgeInsets.all(12),
            child: SingleChildScrollView(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text('THEME PRESETS', style: TextStyle(color: Colors.grey, fontSize: 11, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Wrap(
                    spacing: 6,
                    runSpacing: 6,
                    children: [
                      _buildPresetChip("Cyberpunk", const Color(0xFF0D0D0D), const Color(0xFF121212), const Color(0xFF181818), const Color(0xFF4DEAEA), const Color(0xFF2196F3), const Color(0xFF00FF66)),
                      _buildPresetChip("Dracula", const Color(0xFF141419), const Color(0xFF18181F), const Color(0xFF202028), const Color(0xFFBD93F9), const Color(0xFFFF79C6), const Color(0xFF50FA7B)),
                      _buildPresetChip("Catppuccin", const Color(0xFF121218), const Color(0xFF16161F), const Color(0xFF1E1E26), const Color(0xFF89B4FA), const Color(0xFFCBA6F7), const Color(0xFFA6E3A1)),
                      _buildPresetChip("Nordic Ice", const Color(0xFF15181C), const Color(0xFF1C2026), const Color(0xFF242930), const Color(0xFF88C0D0), const Color(0xFF81A1C1), const Color(0xFFA3BE8C)),
                    ],
                  ),
                  const Divider(height: 24, color: Colors.white24),
                  const Text('COLOR PALETTE CONTROLS', style: TextStyle(color: Colors.grey, fontSize: 11, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 12),

                  _buildColorPicker("Background", _backgroundColor, (c) => setState(() => _backgroundColor = c)),
                  _buildColorPicker("Header / Top Bar", _headerColor, (c) => setState(() => _headerColor = c)),
                  _buildColorPicker("Surface / Card", _surfaceColor, (c) => setState(() => _surfaceColor = c)),
                  _buildColorPicker("Primary Accent", _primaryColor, (c) => setState(() => _primaryColor = c)),
                  _buildColorPicker("Secondary Accent", _secondaryColor, (c) => setState(() => _secondaryColor = c)),
                  _buildColorPicker("Tertiary Accent", _tertiaryColor, (c) => setState(() => _tertiaryColor = c)),
                  _buildColorPicker("Warning / Enterprise", _warningColor, (c) => setState(() => _warningColor = c)),
                  _buildColorPicker("Danger / Critical", _dangerColor, (c) => setState(() => _dangerColor = c)),
                  _buildColorPicker("Text Color", _textColor, (c) => setState(() => _textColor = c)),
                ],
              ),
            ),
          ),

          // Right Column: Live App Preview & Generated XML Box
          Expanded(
            child: Column(
              children: [
                // Top Half: Live App Layout Mockup
                Expanded(
                  flex: 5,
                  child: Container(
                    padding: const EdgeInsets.all(16),
                    color: _backgroundColor,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Text('LIVE APP LAYOUT PREVIEW', style: TextStyle(color: _primaryColor, fontSize: 12, fontWeight: FontWeight.bold)),
                            const Spacer(),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                              decoration: BoxDecoration(color: _surfaceColor, borderRadius: BorderRadius.circular(6), border: Border.all(color: _primaryColor)),
                              child: Text('Device Connected', style: TextStyle(color: _primaryColor, fontSize: 10, fontWeight: FontWeight.bold)),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),

                        // Dropzone Installer Mockup
                        Container(
                          padding: const EdgeInsets.all(14),
                          decoration: BoxDecoration(color: _surfaceColor, borderRadius: BorderRadius.circular(12), border: Border.all(color: _primaryColor.withOpacity(0.4))),
                          child: Row(
                            children: [
                              Icon(Icons.cloud_upload, color: _primaryColor, size: 28),
                              const SizedBox(width: 12),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text('DROP APK FILE HERE TO INSTANTLY INSTALL', style: TextStyle(color: _textColor, fontWeight: FontWeight.bold, fontSize: 13)),
                                    const SizedBox(height: 2),
                                    Text('Supports Android 10-15 version-aware ADB bypass', style: TextStyle(color: _textColor.withOpacity(0.6), fontSize: 11)),
                                  ],
                                ),
                              ),
                              ElevatedButton(
                                style: ElevatedButton.styleFrom(backgroundColor: _primaryColor, foregroundColor: Colors.black),
                                onPressed: () {},
                                child: const Text('SELECT APK', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 11)),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 12),

                        // App Card Preview Row
                        Row(
                          children: [
                            Expanded(
                              child: Container(
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(color: _surfaceColor, borderRadius: BorderRadius.circular(10), border: Border.all(color: _tertiaryColor.withOpacity(0.5))),
                                child: Row(
                                  children: [
                                    Container(
                                      width: 40,
                                      height: 40,
                                      decoration: BoxDecoration(color: _secondaryColor.withOpacity(0.2), borderRadius: BorderRadius.circular(8)),
                                      child: Icon(Icons.android, color: _secondaryColor),
                                    ),
                                    const SizedBox(width: 10),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Text('NewPipe YouTube Client', style: TextStyle(color: _textColor, fontWeight: FontWeight.bold, fontSize: 13)),
                                          Text('org.schabi.newpipe', style: TextStyle(color: _secondaryColor, fontSize: 10)),
                                        ],
                                      ),
                                    ),
                                    Container(
                                      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                      decoration: BoxDecoration(color: _tertiaryColor.withOpacity(0.2), borderRadius: BorderRadius.circular(4), border: Border.all(color: _tertiaryColor)),
                                      child: Text('INSTALLED', style: TextStyle(color: _tertiaryColor, fontSize: 9, fontWeight: FontWeight.bold)),
                                    ),
                                    const SizedBox(width: 6),
                                    IconButton(
                                      icon: Icon(Icons.delete_forever, color: _dangerColor, size: 18),
                                      onPressed: () {},
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),

                // Bottom Half: Generated XML Textbox
                Expanded(
                  flex: 4,
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(12),
                    color: _headerColor,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            const Icon(Icons.code, color: Colors.greenAccent, size: 16),
                            const SizedBox(width: 6),
                            const Text('GENERATED ANDROID MATERIAL 3 XML THEME', style: TextStyle(color: Colors.greenAccent, fontSize: 11, fontWeight: FontWeight.bold)),
                            const Spacer(),
                            Text('Hand this XML text box directly to Antigravity', style: TextStyle(color: Colors.white.withOpacity(0.5), fontSize: 10)),
                          ],
                        ),
                        const SizedBox(height: 6),
                        Expanded(
                          child: Container(
                            padding: const EdgeInsets.all(10),
                            decoration: BoxDecoration(
                              color: Colors.black,
                              borderRadius: BorderRadius.circular(8),
                              border: Border.all(color: Colors.white24),
                            ),
                            child: SelectableText(
                              _generatedXml,
                              style: const TextStyle(color: Color(0xFF00FF66), fontFamily: 'monospace', fontSize: 12),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPresetChip(String label, Color bg, Color header, Color surface, Color pri, Color sec, Color ter) {
    return ActionChip(
      backgroundColor: surface,
      side: BorderSide(color: pri),
      label: Text(label, style: TextStyle(color: pri, fontSize: 10, fontWeight: FontWeight.bold)),
      onPressed: () => _applyPreset(bg, header, surface, pri, sec, ter),
    );
  }

  Widget _buildColorPicker(String label, Color currentColor, Function(Color) onColorChanged) {
    final List<Color> sampleSwatches = [
      const Color(0xFF0B0C10),
      const Color(0xFF10131B),
      const Color(0xFF121622),
      const Color(0xFF4DEAEA),
      const Color(0xFF2196F3),
      const Color(0xFF00FF66),
      const Color(0xFFFFB74D),
      const Color(0xFFFF5252),
      const Color(0xFFBD93F9),
      const Color(0xFFFF79C6),
      const Color(0xFF88C0D0),
      Colors.white,
    ];

    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(width: 14, height: 14, decoration: BoxDecoration(color: currentColor, borderRadius: BorderRadius.circular(3), border: Border.all(color: Colors.white30))),
              const SizedBox(width: 8),
              Text(label, style: const TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.bold)),
              const Spacer(),
              Text("#${currentColor.value.toRadixString(16).substring(2).toUpperCase()}", style: const TextStyle(color: Colors.grey, fontSize: 10, fontFamily: 'monospace')),
            ],
          ),
          const SizedBox(height: 6),
          Wrap(
            spacing: 4,
            runSpacing: 4,
            children: sampleSwatches.map((c) {
              final isSelected = currentColor.value == c.value;
              return GestureDetector(
                onTap: () => onColorChanged(c),
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(
                    color: c,
                    shape: BoxShape.circle,
                    border: isSelected ? Border.all(color: Colors.white, width: 2) : Border.all(color: Colors.black45),
                  ),
                ),
              );
            }).toList(),
          ),
        ],
      ),
    );
  }
}
